function MainMenu()
    % MAINMENU - Glove type selection GUI
    % Opens a launcher page with glove material choices.

    fig = uifigure('Name', 'Glove Detection - Main Menu', ...
                   'Position', [500 220 600 430], ...
                   'Color', [0.96 0.97 0.99]);

    uilabel(fig, ...
            'Text', 'Select Glove Type', ...
            'FontSize', 28, ...
            'FontWeight', 'bold', ...
            'FontColor', [0.08 0.23 0.45], ...
            'HorizontalAlignment', 'center', ...
            'Position', [160 355 280 42]);

    uilabel(fig, ...
            'Text', 'Choose a glove material to continue', ...
            'FontSize', 14, ...
            'FontColor', [0.33 0.37 0.42], ...
            'HorizontalAlignment', 'center', ...
            'Position', [165 326 270 24]);

    btnW = 210;
    btnH = 56;
    x1 = 95;
    x2 = 295;
    y1 = 220;
    y2 = 140;

    uibutton(fig, 'push', ...
             'Text', 'Rubber Nitrile', ...
             'FontSize', 16, ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.09 0.60 0.99], ...
             'FontColor', [1 1 1], ...
             'Position', [x1 y1 btnW btnH], ...
             'ButtonPushedFcn', @openRubberNitrile);

    uibutton(fig, 'push', ...
             'Text', 'Latex', ...
             'FontSize', 16, ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.31 0.56 0.78], ...
             'FontColor', [1 1 1], ...
             'Position', [x2 y1 btnW btnH], ...
             'ButtonPushedFcn', @openLatex);

    uibutton(fig, 'push', ...
             'Text', 'Nylon', ...
             'FontSize', 16, ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.25 0.50 0.72], ...
             'FontColor', [1 1 1], ...
             'Position', [x1 y2 btnW btnH], ...
             'ButtonPushedFcn', @(~,~)showComingSoon('Nylon'));

    uibutton(fig, 'push', ...
             'Text', 'Cotton', ...
             'FontSize', 16, ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.28 0.53 0.75], ...
             'FontColor', [1 1 1], ...
             'Position', [x2 y2 btnW btnH], ...
             'ButtonPushedFcn', @(~,~)showComingSoon('Cotton'));

    uibutton(fig, 'push', ...
             'Text', 'Close', ...
             'FontSize', 13, ...
             'BackgroundColor', [1 0 0], ...
             'FontColor', [1 1 1], ...
             'Position', [255 48 90 32], ...
             'ButtonPushedFcn', @(~,~)delete(fig));

    function openRubberNitrile(~, ~)
        % Launch existing App Designer GUI for Rubber Nitrile pipeline.
        try
            % Add parent and RubberNitrileGloves folders to path
            addpath(pwd);  % Parent directory for shared utilities
            rubberPath = fullfile(pwd, 'RubberNitrileGloves');
            addpath(rubberPath);
            % Create and display the app
            app = RubberNitrile_GUI_exported();
            % Delete main menu after GUI is created
            delete(fig);
        catch ME
            % If error occurs, show it
            uialert(fig, sprintf('Error launching Rubber Nitrile GUI:\n%s', ME.message), 'Error');
        end
    end

    function openLatex(~, ~)
        % Launch App Designer GUI for Latex pipeline.
        try
            % Add parent and LatexGloves folders to path
            addpath(pwd);  % Parent directory for shared utilities
            latexPath = fullfile(pwd, 'LatexGloves');
            addpath(latexPath);
            % Create and display the app
            app = idkGlove_GUI();
            % Delete main menu after GUI is created
            delete(fig);
        catch ME
            % If error occurs, show it
            uialert(fig, sprintf('Error launching Latex GUI:\n%s', ME.message), 'Error');
        end
    end

    function showComingSoon(gloveType)
        uialert(fig, sprintf('%s module is not connected yet.', gloveType), 'Coming Soon');
    end
end
